---
title: Wijzig het thema en lettertype in Thonny
hero_image: images/banner.png
description: Wijzig het thema en lettertype in Thonny
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: Wijzig het thema en lettertype in Thonny
