---
title: Change the theme and font in Thonny
hero_image: images/banner.png
description: Change the theme and font in Thonny
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - 
    title: Change the theme and font in Thonny
