---
title: تغيير الموضوع والخط في Thonny
hero_image: images/banner.png
description: تغيير الموضوع والخط في Thonny
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: تغيير الموضوع والخط في Thonny
