---
title: Ändra tema och typsnitt i Thonny
hero_image: images/banner.png
description: Ändra tema och typsnitt i Thonny
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - 
    title: Ändra tema och typsnitt i Thonny
