---
title: Changer le thème et la police dans Thonny
hero_image: images/banner.png
description: Changer le thème et la police dans Thonny
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - 
    title: Changer le thème et la police dans Thonny
